apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
        app: bookstore
        tier: frontend
  template:
    metadata:
      labels:
        app: bookstore
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: "quay.io/mromdhani/bookstore-front"
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: bookstore
    tier: frontend
  ports:
    - port: 8888
      targetPort: 80

